import { Platform } from "react-native";
import * as FileSystem from "expo-file-system/legacy";
import Share from "react-native-share";

/**
 * Report Service - Generación y exportación de reportes
 */

export interface ReportData {
  title: string;
  timestamp: Date;
  type: "wifi" | "bluetooth" | "audit" | "comprehensive";
  summary: string;
  details: Record<string, any>;
  recommendations: string[];
  riskLevel: "critical" | "high" | "medium" | "low";
}

class ReportService {
  /**
   * Generar reporte en formato texto
   */
  generateTextReport(data: ReportData): string {
    const lines: string[] = [];

    // Header
    lines.push("=".repeat(60));
    lines.push(`IL0veMyTool - ${data.type.toUpperCase()} Report`);
    lines.push("=".repeat(60));
    lines.push("");

    // Información general
    lines.push("GENERAL INFORMATION");
    lines.push("-".repeat(60));
    lines.push(`Title: ${data.title}`);
    lines.push(`Date: ${data.timestamp.toISOString()}`);
    lines.push(`Risk Level: ${data.riskLevel.toUpperCase()}`);
    lines.push(`Summary: ${data.summary}`);
    lines.push("");

    // Detalles
    lines.push("DETAILS");
    lines.push("-".repeat(60));
    Object.entries(data.details).forEach(([key, value]) => {
      if (typeof value === "object") {
        lines.push(`${key}:`);
        Object.entries(value).forEach(([k, v]) => {
          lines.push(`  ${k}: ${v}`);
        });
      } else {
        lines.push(`${key}: ${value}`);
      }
    });
    lines.push("");

    // Recomendaciones
    if (data.recommendations.length > 0) {
      lines.push("RECOMMENDATIONS");
      lines.push("-".repeat(60));
      data.recommendations.forEach((rec, index) => {
        lines.push(`${index + 1}. ${rec}`);
      });
      lines.push("");
    }

    // Footer
    lines.push("=".repeat(60));
    lines.push("Generated by IL0veMyTool");
    lines.push("=".repeat(60));

    return lines.join("\n");
  }

  /**
   * Generar reporte en formato HTML
   */
  generateHtmlReport(data: ReportData): string {
    const riskColor = {
      critical: "#FF4D4D",
      high: "#FFB020",
      medium: "#FFA500",
      low: "#00FFA3",
    };

    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${data.title}</title>
  <style>
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      background: #0B0F14;
      color: #E6EDF3;
      padding: 20px;
      margin: 0;
    }
    .container {
      max-width: 900px;
      margin: 0 auto;
      background: #121821;
      border: 1px solid #334155;
      border-radius: 8px;
      padding: 30px;
    }
    .header {
      border-bottom: 2px solid #00E5FF;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    h1 {
      color: #00E5FF;
      margin: 0 0 10px 0;
      font-size: 28px;
    }
    .meta {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 15px;
      margin-top: 15px;
    }
    .meta-item {
      background: #1A2330;
      padding: 10px;
      border-radius: 4px;
      border-left: 3px solid #00E5FF;
    }
    .meta-label {
      color: #8B949E;
      font-size: 12px;
      text-transform: uppercase;
    }
    .meta-value {
      color: #E6EDF3;
      font-size: 14px;
      font-weight: 600;
      margin-top: 5px;
    }
    .risk-badge {
      display: inline-block;
      padding: 8px 16px;
      border-radius: 20px;
      font-weight: bold;
      background: ${riskColor[data.riskLevel]}33;
      color: ${riskColor[data.riskLevel]};
      border: 1px solid ${riskColor[data.riskLevel]};
    }
    section {
      margin-bottom: 30px;
    }
    h2 {
      color: #00E5FF;
      border-bottom: 1px solid #334155;
      padding-bottom: 10px;
      margin-bottom: 15px;
      font-size: 18px;
    }
    .details-grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 15px;
    }
    .detail-item {
      background: #1A2330;
      padding: 15px;
      border-radius: 4px;
      border-left: 3px solid #7C4DFF;
    }
    .detail-label {
      color: #8B949E;
      font-size: 12px;
      text-transform: uppercase;
    }
    .detail-value {
      color: #E6EDF3;
      font-size: 14px;
      margin-top: 5px;
      word-break: break-all;
    }
    .recommendations {
      background: #1A2330;
      padding: 15px;
      border-radius: 4px;
      border-left: 3px solid #00FFA3;
    }
    .recommendations ol {
      margin: 10px 0;
      padding-left: 20px;
    }
    .recommendations li {
      margin-bottom: 8px;
      color: #E6EDF3;
    }
    .footer {
      text-align: center;
      color: #8B949E;
      font-size: 12px;
      border-top: 1px solid #334155;
      padding-top: 20px;
      margin-top: 30px;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>${data.title}</h1>
      <div class="meta">
        <div class="meta-item">
          <div class="meta-label">Report Type</div>
          <div class="meta-value">${data.type.toUpperCase()}</div>
        </div>
        <div class="meta-item">
          <div class="meta-label">Risk Level</div>
          <div class="meta-value"><span class="risk-badge">${data.riskLevel.toUpperCase()}</span></div>
        </div>
        <div class="meta-item">
          <div class="meta-label">Generated</div>
          <div class="meta-value">${data.timestamp.toLocaleString()}</div>
        </div>
        <div class="meta-item">
          <div class="meta-label">Summary</div>
          <div class="meta-value">${data.summary}</div>
        </div>
      </div>
    </div>

    <section>
      <h2>Details</h2>
      <div class="details-grid">
        ${Object.entries(data.details)
          .map(
            ([key, value]) => `
          <div class="detail-item">
            <div class="detail-label">${key}</div>
            <div class="detail-value">${
              typeof value === "object"
                ? JSON.stringify(value, null, 2)
                : value
            }</div>
          </div>
        `
          )
          .join("")}
      </div>
    </section>

    ${
      data.recommendations.length > 0
        ? `
    <section>
      <h2>Recommendations</h2>
      <div class="recommendations">
        <ol>
          ${data.recommendations.map((rec) => `<li>${rec}</li>`).join("")}
        </ol>
      </div>
    </section>
    `
        : ""
    }

    <div class="footer">
      <p>Generated by IL0veMyTool - Network Auditor & Security Scanner</p>
      <p>© 2026 IL0veMyTool. All rights reserved.</p>
    </div>
  </div>
</body>
</html>
    `;

    return html;
  }

  /**
   * Guardar reporte como archivo
   */
  async saveReport(
    data: ReportData,
    format: "txt" | "html" = "html"
  ): Promise<string> {
    try {
      const timestamp = data.timestamp.toISOString().split("T")[0];
      const filename = `report-${data.type}-${timestamp}.${format}`;
      const filepath = `${FileSystem.documentDirectory ?? ""}${filename}`;

      const content =
        format === "html"
          ? this.generateHtmlReport(data)
          : this.generateTextReport(data);

      await FileSystem.writeAsStringAsync(filepath, content);
      return filepath;
    } catch (error) {
      console.error("Error saving report:", error);
      throw error;
    }
  }

  /**
   * Compartir reporte
   */
  async shareReport(
    data: ReportData,
    format: "txt" | "html" = "html"
  ): Promise<void> {
    try {
      let filepath = "";
      try {
        filepath = await this.saveReport(data, format);
      } catch (e) {
        // En web, no hay filepath
      }
      const content =
        format === "html"
          ? this.generateHtmlReport(data)
          : this.generateTextReport(data);

      if (Platform.OS === "web") {
        // Para web, crear un blob y descargar
        const blob = new Blob([content], {
          type:
            format === "html" ? "text/html" : "text/plain",
        });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `report-${data.type}-${Date.now()}.${format}`;
        a.click();
        URL.revokeObjectURL(url);
      } else {
        // Para mobile, usar react-native-share
        await Share.open({
          title: `Share ${data.title}`,
          message: content,
          url: filepath,
          type: format === "html" ? "text/html" : "text/plain",
        });
      }
    } catch (error) {
      console.error("Error sharing report:", error);
      throw error;
    }
  }

  /**
   * Generar reporte completo
   */
  generateComprehensiveReport(
    wifiData: any,
    bluetoothData: any,
    auditData: any
  ): ReportData {
    const recommendations: string[] = [];
    let riskLevel: "critical" | "high" | "medium" | "low" = "low";

    // Analizar riesgos
    if (wifiData?.openNetworks > 0) {
      recommendations.push("Secure open WiFi networks with WPA3 encryption");
      riskLevel = "critical";
    }

    if (auditData?.criticalPorts > 0) {
      recommendations.push(
        "Close unnecessary ports and restrict access to critical services"
      );
      riskLevel = "critical";
    }

    if (auditData?.unknownDevices > 0) {
      recommendations.push(
        "Investigate unknown devices connected to your network"
      );
      if (riskLevel !== "critical") riskLevel = "high";
    }

    if (bluetoothData?.unpairedDevices > 0) {
      recommendations.push("Review unpaired Bluetooth devices in range");
      if (riskLevel === "low") riskLevel = "medium";
    }

    return {
      title: "Network Security Audit Report",
      timestamp: new Date(),
      type: "comprehensive",
      summary: "Complete network security analysis",
      details: {
        wifi: wifiData,
        bluetooth: bluetoothData,
        audit: auditData,
      },
      recommendations,
      riskLevel,
    };
  }
}

export const reportService = new ReportService();
